import { fmt } from './format'
import { typeLabels, statusColors } from './constants'

export function genPDF(inv, name) {
  const w = window.open('', '_blank')
  const audit = inv.auditLog?.map(a => `<p style="font-size:11px;color:#888">${a.at} - ${a.action} by ${a.by}</p>`).join('') || ''
  const caseInfo = inv.caseInfo
    ? `<div style="margin:20px 0;padding:15px;background:#f9fafb;border-radius:8px"><p style="margin:0 0 10px;font-weight:bold;color:#374151">Event Information</p><table style="width:100%;font-size:14px"><tr><td style="padding:4px 0;color:#6b7280">Event Name:</td><td style="padding:4px 0">${inv.caseInfo.caseName || '-'}</td><td style="padding:4px 0;color:#6b7280">Deposition Event ID:</td><td style="padding:4px 0">${inv.caseInfo.jobNumber || '-'}</td></tr><tr><td style="padding:4px 0;color:#6b7280">Date:</td><td style="padding:4px 0" colspan="3">${inv.caseInfo.jobDate || '-'}</td></tr><tr><td style="padding:4px 0;color:#6b7280">RB9 Job #:</td><td style="padding:4px 0" colspan="3">${inv.caseInfo.rb9JobNumber || '-'}</td></tr></table></div>${inv.invoiceComment ? `<div style="margin:10px 0;padding:12px 15px;background:#fff7ed;border:1px solid #fed7aa;border-radius:8px"><p style="margin:0 0 4px;font-weight:bold;color:#92400e;font-size:13px">Notes / Comments</p><p style="margin:0;font-size:14px;color:#78350f">${inv.invoiceComment}</p></div>` : ''}`
    : ''
  w.document.write(`<html><head><title>${inv.invoiceNumber}</title><style>body{font-family:Arial;padding:40px;max-width:700px;margin:auto}table{width:100%;border-collapse:collapse;margin:20px 0}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}th{background:#f5f5f5}.right{text-align:right}.type{display:inline-block;padding:4px 12px;border-radius:12px;font-size:12px;background:#f3f4f6}.agency{background:#eef2ff;border:1px solid #c7d2fe;padding:12px;border-radius:8px;margin:15px 0}</style></head><body><h1 style="color:#1e40af">${inv.invoiceNumber}</h1><p><span class="type">${typeLabels[inv.invoiceType] || 'Standard'}</span></p><div class="agency"><p style="margin:0;font-weight:bold;color:#4338ca">Invoicing for: Filevine</p></div><p><b>Reporter:</b> ${name}</p><p><b>Status:</b> ${inv.status}</p>${inv.approvedBy ? `<p><b>Approved:</b> ${inv.approvedAt} by ${inv.approvedBy}</p>` : ''}${inv.paidBy ? `<p><b>Paid:</b> ${inv.paidAt} by ${inv.paidBy}</p>` : ''}${caseInfo}<table><tr><th>Description</th><th class="right">Qty</th><th class="right">Rate</th><th class="right">Amount</th></tr>${inv.lineItems.map(l => `<tr><td>${l.description}</td><td class="right">${l.qty}</td><td class="right">${fmt(l.unitCents)}</td><td class="right">${fmt(l.amountCents)}</td></tr>`).join('')}<tr style="font-weight:bold"><td colspan="3">Total</td><td class="right">${fmt(inv.totalCents)}</td></tr></table>${audit ? `<h3>Audit Trail</h3>${audit}` : ''}<script>window.print()<\/script></body></html>`)
  w.document.close()
}
